version: '3'
services:
  frontend:
    build: 
      context: ./main
      dockerfile: Dockerfile.apache
    volumes:
      - ./main/src/:/var/www/html/
    hostname: frontend.internal
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile.apache
    volumes:
      - /var/www/html/
    hostname: backend.internal
  money-transfer:
    build: 
      context: ./money-transfer
      dockerfile: Dockerfile.apache
    volumes:
      - /var/www/html/
    hostname: money-transfer.internal
  refer-a-friend:
    build: 
      context: ./refer-a-friend
      dockerfile: Dockerfile.apache
    volumes:
      - /var/www/html/
    hostname: refer-a-friend.internal
  nginx:
    build: 
      context: ./nginx-reverse-proxy
    ports: 
      - 3080:80
    depends_on:
      - frontend
      - backend
  mortgage:
    build: 
      context: ./mortgage-calculator
      dockerfile: Dockerfile.apache
    volumes:
      - /var/www/html/
    hostname: mortgage-calculator.internal

  # openbanking:
  #   hostname: openbanking.internal
  #   build: 
  #     context: ./openbanking
  #     dockerfile: Dockerfile.nuapay

  # openbanking:
  #   build: 
  #     context: ./openbanking
  #     dockerfile: Dockerfile.postman
  #     environment:
  #       BASE_URL: https://business-partner.acmecorp-prod.f5-cloud-demo.com/openbanking