version: '3'
services:
  arcadia-frontend:
    build: 
      context: ./main
    volumes:
      - ./main/MainApp:/var/www/html/
    ports: 
      - 3081:80  
    environment:
      PMA_HOST: localhost
  arcadia-backend:
    build: 
      context: ./backend
    volumes:
      - ./backend/files/:/var/www/html/files/
    ports: 
      - 3082:80    
  arcadia-money-transfer:
    build: 
      context: ./app2
    volumes:
      - ./app2/api/:/var/www/html/api/
  arcadia-refer-a-friend:
    build: 
      context: ./app3
    volumes:
      - ./app3/app3/:/var/www/html/app3/
    ports: 
      - 3083:80          
  nginx:
    build: 
      context: ./Nginx
    ports: 
      - 3080:80