version: '3'
services:
  frontend:
    build: 
      context: ./main
      dockerfile: Dockerfile.apache
    volumes:
      - /var/www/html/
    hostname: frontend.internal
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile.apache
    volumes:
      - /var/www/html/
    hostname: backend.internal
  money-transfer:
    build: 
      context: ./money-transfer
      dockerfile: Dockerfile.apache
    volumes:
      - /var/www/html/
    hostname: money-transfer.internal
  refer-a-friend:
    build: 
      context: ./refer-a-friend
      dockerfile: Dockerfile.apache
    volumes:
      - /var/www/html/
    hostname: refer-a-friend.internal
  nginx:
    build: 
      context: ./nginx-reverse-proxy
    ports: 
      - 3080:80
    depends_on:
      - frontend
      - backend
  # mortgage-fastcgi:
  #   build: 
  #     context: ./mortgage-calculator
  #     dockerfile: phpfpm.Dockerfile
  #   volumes:
  #     - ./mortgage-calculator/mortgage/:/usr/share/nginx/html/mortgage/
  #   hostname: fastcgi
  # mortgage-nginx:
  #   build: 
  #     context: ./mortgage-calculator
  #     dockerfile: nginx.Dockerfile      
  #   volumes:
  #     - ./mortgage-calculator/mortgage/:/usr/share/nginx/html/mortgage/      
  #   ports: 
  #    - 5080:8080
  #   hostname: mortgage-nginx.internal
  #   depends_on:
  #     - mortgage-fastcgi     
  # openbanking:
  #   hostname: openbanking.internal
  #   build: 
  #     context: ./openbanking
  #     dockerfile: Dockerfile.nuapay

  # openbanking:
  #   build: 
  #     context: ./openbanking
  #     dockerfile: Dockerfile.postman
  #     environment:
  #       BASE_URL: https://business-partner.acmecorp-prod.f5-cloud-demo.com/openbanking