version: '3'
services:
  frontend:
    build: 
      context: ./main
    volumes:
      - ./main/MainApp:/var/www/html/
    ports: 
      - 3081:80  
    environment:
      PMA_HOST: localhost
  backend:
    build: 
      context: ./backend
    volumes:
      - ./backend/files/:/var/www/html/files/
    ports: 
      - 3082:80    
  money-transfer:
    build: 
      context: ./app2
    volumes:
      - ./app2/api/:/var/www/html/api/
  refer-a-friend:
    build: 
      context: ./app3
    volumes:
      - ./app3/app3/:/var/www/html/app3/
    ports: 
      - 3083:80          
  nginx:
    build: 
      context: ./Nginx
    ports: 
      - 3080:80
    depends_on:
      - frontend
      - backend
  mortgage-fastcgi:
    build: 
      context: ./mortgage-calculator
      dockerfile: phpfpm.Dockerfile
    volumes:
      - ./mortgage-calculator/mortgage/:/usr/share/nginx/html/mortgage/
  mortgage-nginx:
    build: 
      context: ./mortgage-calculator
      dockerfile: nginx.Dockerfile      
    volumes:
      - ./mortgage-calculator/mortgage/:/usr/share/nginx/html/mortgage/      
    ports: 
     - 5080:8080
    depends_on:
      - mortgage-fastcgi     