version: '3'
services:
  arcadia-frontend:
    image: interestingstorage/arcadia-frontend:v1
    volumes:
      - ./main/MainApp:/var/www/html/
    ports: 
      - 3081:80  
    environment:
      PMA_HOST: localhost
  backend:
    image: interestingstorage/arcadia-backend:v1
    volumes:
      - ./backend/files/:/var/www/html/files/
    ports: 
      - 3082:80    
  arcadia-money-transfer:
    image: interestingstorage/arcadia-money-transfer:v1
    volumes:
      - ./app2/api/:/var/www/html/api/
  arcadia-refer-a-friend:
    image: interestingstorage/arcadia-refer-a-friend:v1
    volumes:
      - ./app3/app3/:/var/www/html/app3/
    ports: 
      - 3083:80          
  nginx:
    image: interestingstorage/arcadia-reverse-proxy:v1
    pull_policy: always
    ports: 
      - 3080:80
    depends_on:
      - arcadia-frontend
      - backend