version: '3.8'
services:
  frontend:
    hostname: frontend.internal
    image: interestingstorage/arcadia-frontend:isc-2021
    environment:
      PMA_HOST: localhost
    restart: always
    logging:
        driver: "json-file"
        options:
            max-file: "5"
            max-size: "10m"
  backend:
    hostname: backend.internal
    image: interestingstorage/arcadia-backend:isc-2021
    environment:
      PMA_HOST: localhost
    restart: always
    logging:
        driver: "json-file"
        options:
            max-file: "5"
            max-size: "10m"
  reverse-proxy:
    image: interestingstorage/arcadia-reverse-proxy:isc-2021
    ports: 
      - 80:80
    extra_hosts:
      - "money-transfer.internal:172.1.1.4"
    restart: always
    logging:
        driver: "json-file"
        options:
            max-file: "5"
            max-size: "10m"
    depends_on:
      - frontend
      - backend      