version: '3.8'
services:
  money-transfer:
    hostname: money-transfer.internal
    image: interestingstorage/arcadia-money-transfer:isc-2021
    ports: 
      - 80:80     
    extra_hosts:
      - "backend:10.0.1.230"
    restart: always
    logging:
        driver: "json-file"
        options:
            max-file: "5"
            max-size: "10m"
  refer-a-friend:
    hostname: refer-a-friend.internal
    image: interestingstorage/arcadia-refer-a-friend:isc-2021
    environment:
      PMA_HOST: localhost  
    ports: 
      - 8081:80              
    restart: always
    logging:
        driver: "json-file"
        options:
            max-file: "5"
            max-size: "10m"
  transaction-api:
    image: docker.io/interestingstorage/arcadia-nua-api:isc-2021
    ports: 
      - 8082:8080
    restart: always
    logging:
        driver: "json-file"
        options:
            max-file: "5"
            max-size: "10m"