version: '3'
services:
  refer-a-friend:
    hostname: refer-a-friend.internal
    image: interestingstorage/arcadia-refer-a-friend:v1
    environment:
      PMA_HOST: localhost  
    ports: 
      - 80:80              
    restart: always