{
  "openapi": "3.0.1",
  "info": {
    "title": "Nuapay TPP API Specification",
    "description": "Swagger Spec for the Nuapay TPP OpenBanking/PSD2. Provides PISP and Banks Endpoints",
    "contact": {
      "name": "Nuapay",
      "email": "api.support@nuapay.com"
    },
    "license": {
      "name": "Nuapay",
      "url": "https://sentenial.com"
    },
    "version": "1.14.4",
    "x-logo": {
      "backgroundColor": "#FFFFFF",
      "url": "https://www.nuapay.com/wp-content/uploads/2018/04/nuapay.svg"
    }
  },
  "servers": [
    {
      "url": "https://api.nuapay.com/tpp"
    }
  ],
  "tags": [
    {
      "name": "Bank Service",
      "description": "Bank endpoints allow a merchant to,\n- Retrieve a list of banks that support the Open Banking scheme\n- View details of a specific bank that supports the Open Banking scheme"
    },
    {
      "name": "PISP Service",
      "description": "Payment initiation endpoints allow a merchant to,\n- Initiate payment requests in Open Banking\n- Retrieve the status of a previously initiated payment request"
    }
  ],
  "paths": {
    "/accounts": {
      "get": {
        "tags": [
          "Account Service"
        ],
        "summary": "View Bank Account",
        "description": "Get list of Bank Families",
        "operationId": "getBankFamiliesUsingGET",
        "security": [
          {
            "MerchantOAuth2": [
              "openbanking_aisp",
              "openbanking_pisp"
            ]
          },
          {
            "MerchantApiKey": []
          },
          {
            "PartnerOAuth2": [
              "openbanking_aisp",
              "openbanking_pisp"
            ]
          },
          {
            "PartnerApiKey": []
          }
        ]
      }
    },
    "/sccounts/{accountId}": {
      "get": {
        "tags": [
          "Bank Service"
        ],
        "summary": "View Bank Family",
        "description": "View Bank Family Details",
        "operationId": "getBankFamilyUsingGET",
        "security": [
          {
            "MerchantOAuth2": [
              "openbanking_aisp",
              "openbanking_pisp"
            ]
          },
          {
            "MerchantApiKey": []
          },
          {
            "PartnerOAuth2": [
              "openbanking_aisp",
              "openbanking_pisp"
            ]
          },
          {
            "PartnerApiKey": []
          }
        ]
      }
    },
    "/banks": {
      "get": {
        "tags": [
          "Bank Service"
        ],
        "summary": "Retrieve Banks",
        "description": "Get Supported Banks On This TPP",
        "operationId": "getBanksUsingGET",
        "security": [
          {
            "MerchantOAuth2": [
              "openbanking_aisp",
              "openbanking_pisp"
            ]
          },
          {
            "MerchantApiKey": []
          },
          {
            "PartnerOAuth2": [
              "openbanking_aisp",
              "openbanking_pisp"
            ]
          },
          {
            "PartnerApiKey": []
          }
        ]
      }
    },
    "/payments": {
      "get": {
        "tags": [
          "PISP Service"
        ],
        "summary": "List payments",
        "description": "GET payments list endpoint",
        "operationId": "getPaymentListUsingGet",
        "security": [
          {
            "MerchantOAuth2": [
              "openbanking_pisp"
            ]
          },
          {
            "MerchantApiKey": []
          },
          {
            "PartnerOAuth2": [
              "openbanking_pisp"
            ]
          },
          {
            "PartnerApiKey": []
          }
        ]
      },
      "post": {
        "tags": [
          "PISP Service"
        ],
        "summary": "Create Payment",
        "description": "Create a payment request POST endpoint",
        "operationId": "createPaymentUsingPOST",
        "security": [
          {
            "MerchantOAuth2": [
              "openbanking_aisp",
              "openbanking_pisp"
            ]
          },
          {
            "MerchantApiKey": []
          }
        ]
      }
    },
    "/payments/callback": {
      "post": {
        "tags": [
          "PISP Service"
        ],
        "summary": "Forward Payment Callback",
        "description": "Forward Payment Callback POST endpoint",
        "operationId": "forwardPaymentCallbackPOST",
        "security": [
          {
            "MerchantOAuth2": [
              "openbanking_callback"
            ]
          },
          {
            "PartnerOAuth2": [
              "openbanking_callback"
            ]
          }
        ]
      }
    },
    "/payments/{paymentId}": {
      "get": {
        "tags": [
          "PISP Service"
        ],
        "summary": "Retrieve Payment",
        "description": "GET Payment details endpoint",
        "operationId": "getPaymentUsingGET",
        "security": [
          {
            "MerchantOAuth2": [
              "openbanking_pisp"
            ]
          },
          {
            "MerchantApiKey": []
          }
        ]
      },
      "patch": {
        "tags": [
          "PISP Service"
        ],
        "summary": "Retry Payment",
        "description": "Retry Payment",
        "operationId": "setBankIdForPaymentUsingPATCH",
        "security": [
          {
            "MerchantOAuth2": [
              "openbanking_pisp"
            ]
          }
        ]
      }
    },
    "/payments/{paymentId}/history": {
      "get": {
        "tags": [
          "PISP Service"
        ],
        "summary": "Retrieve Payment  History",
        "description": "Retrieve Payment History",
        "operationId": "getPaymentHistoryUsingGET",
        "security": [
          {
            "MerchantOAuth2": [
              "openbanking_pisp_read"
            ]
          },
          {
            "MerchantApiKey": []
          }
        ]
      }
    },
    "/payments/{paymentId}/refunds": {
      "get": {
        "tags": [
          "PISP Service"
        ],
        "summary": "List Payment Refunds",
        "description": "List refunds using GET",
        "operationId": "listRefundsUsingGET",
        "security": [
          {
            "MerchantOAuth2": [
              "openbanking_pisp"
            ]
          },
          {
            "MerchantApiKey": []
          }
        ]
      },
      "post": {
        "tags": [
          "PISP Service"
        ],
        "summary": "Refund Payment",
        "description": "Refund a payment using POST",
        "operationId": "refundPaymentUsingPOST",
        "security": [
          {
            "MerchantOAuth2": [
              "openbanking_refund"
            ]
          },
          {
            "MerchantApiKey": []
          }
        ]
      }
    },
    "/payments/{paymentId}/refunds/{refundId}": {
      "get": {
        "tags": [
          "PISP Service"
        ],
        "summary": "Retrieve Refund",
        "description": "GET Refund details endpoint",
        "operationId": "getRefundUsingGET",
        "security": [
          {
            "MerchantOAuth2": [
              "openbanking_refund_read"
            ]
          },
          {
            "MerchantApiKey": []
          }
        ]
      }
    }
  },
  "components": {
    "securitySchemes": {
      "MerchantApiKey": {
        "type": "http",
        "scheme": "basic"
      },
      "PartnerApiKey": {
        "type": "http",
        "scheme": "basic"
      },
      "MerchantOAuth2": {
        "type": "http",
        "scheme": "bearer"
      },
      "PartnerOAuth2": {
        "type": "http",
        "scheme": "bearer"
      }
    }
  }
}