version: '3.8'
services:
  money-transfer:
    hostname: money-transfer.internal
    image: interestingstorage/arcadia-money-transfer:isc-2021
    ports: 
      - 80:80     
    extra_hosts:
      - "backend:172.24.10.94"
    restart: always
    logging:
        driver: "json-file"
        options:
            max-file: "5"
            max-size: "10m"
  test-tool:
    image: interestingstorage/arcadia-connectivity-tool:isc-2021
    ports:
      - 8081:8080
    restart: always
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"

  transaction-api:
    image: docker.io/interestingstorage/arcadia-nua-api:isc-2021
    ports: 
      - 8082:80
    restart: always
    logging:
        driver: "json-file"
        options:
            max-file: "5"
            max-size: "10m"
  