apiVersion: v1
kind: Secret
metadata:
  name: dockerio
data:
  .dockerconfigjson: eyJhdXRocyI6eyJkb2NrZXIuaW8iOnsidXNlcm5hbWUiOiJpbnRlcmVzdGluZ3N0b3JhZ2UiLCJwYXNzd29yZCI6IjMwZTRjYThmLWEwMzUtNDRkNS1hZDQyLWY5NDg3YjcwMjFiNSIsImF1dGgiOiJhVzUwWlhKbGMzUnBibWR6ZEc5eVlXZGxPak13WlRSallUaG1MV0V3TXpVdE5EUmtOUzFoWkRReUxXWTVORGczWWpjd01qRmlOUT09In19fQ==
type: kubernetes.io/dockerconfigjson
---
apiVersion: v1
kind: Service
metadata:
  name: arcadia-mortgage-calculator
spec:
  type: ClusterIP
  selector:
    app: arcadia-mortgage-calculator
  ports:
    - name: http
      port: 80
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: arcadia-mortgage-calculator
spec:
  selector:
    matchLabels:
      app: arcadia-mortgage-calculator
  template:
    metadata:
      labels:
        app: arcadia-mortgage-calculator      
    spec:
      volumes:
        - name: web-data
          emptyDir: {}
      hostAliases:
        # - ip: "127.0.0.1"
        #   hostnames:
        #     - "fastcgi"
      containers:
        - name: nginx
          image: docker.io/interestingstorage/arcadia-mortgage-calculator:vk8s-isc-2021
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          command: ["/bin/sh","-c"]
          args: ["cp -r /usr/share/nginx/html/* /mnt/web/web-data/ && nginx -g 'daemon off;'"]
          volumeMounts:
            - name: web-data
              mountPath: /mnt/web/web-data/       
        - name: phpfpm
          image: docker.io/interestingstorage/arcadia-phpfpm:vk8s-isc-2021
          imagePullPolicy: Always
          ports:
            - containerPort: 9000
          volumeMounts:
            - name: web-data
              mountPath: /mnt/web/web-data/                
      imagePullSecrets:
        - name: dockerio
---
apiVersion: v1
kind: Service
metadata:
  name: test-tool
spec:
  type: ClusterIP
  selector:
    app: test-tool
  ports:
    - name: http
      port: 8081
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-tool
spec:
  selector:
    matchLabels:
      app: test-tool
  template:
    metadata:
      labels:
        app: test-tool
    spec:
      volumes:
        - name: web-data
          emptyDir: {}
      hostAliases:
        - ip: "127.0.0.1"
          hostnames:
            - "fastcgi"
      containers:
        - name: nginx
          image: docker.io/interestingstorage/arcadia-connectivity-tool:isc-2021
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
      imagePullSecrets:
        - name: dockerio